### ISSUE TITLE
リセット＆シャッフル機能

### ISSUE THREAD

**Issue by domasyake** [sofmelauncher/Launcher#15]
タイマーを機能させるためお客さんが席を立ったタイミングで何らかのキーを押させタイマーをリセットしてもらう。また公平性の観点とクレームが来ても困るのでリセット時にランダムに選択中ゲームを切り替える

**Comment by su-u** [comment]
ファンクションキーは筐体によってメディアキーの動作をするが、展示用キーボードが接続されるのであれば、問題ないと思われる。

**Comment by domasyake** [comment]
了。適当に乱数回スライドさせるだけだけど
e1ebcff
