### ISSUE TITLE
ログをローカルサーバーに送りつける

### ISSUE THREAD

**Issue by su-u** [sofmelauncher/Launcher#20]
まとめるとができれば、問題をすぐに発見できる。最終的に収集する手間がなくなる。
文化の祭典を目標に検討。

**Comment by domasyake** [comment]
問題を発見したところで結局のとこランチャー班はブースに常駐することにはなるからメインは収集の方になりそうな

**Comment by su-u** [comment]
https://github.com/sofmelauncher/Launcher/tree/feature-server-post
実装
