### ISSUE TITLE
UIデザイン

### ISSUE THREAD

**Issue by sofmelauncher** [sofmelauncher/Launcher#3]

**Comment by su-u** [comment]
![image](https://user-images.githubusercontent.com/30166652/40909148-d758d08e-6823-11e8-9687-76305104ec90.jpg)
大体決定！！

**Comment by su-u** [comment]
![image](https://user-images.githubusercontent.com/30166652/40909547-cc10bc36-6824-11e8-982a-82a8d08ca549.png)
