### ISSUE TITLE
ゲーム監視の詳細

### ISSUE THREAD

**Issue by domasyake** [sofmelauncher/Launcher#9]
前回では起動回数、時間、リソース使用率の監視を行ったが今回も行うかどうか

**Comment by su-u** [comment]
余裕があれば行いたい。
+ランチャーの改善に役に立つデータが取れないか検討。

**Comment by domasyake** [comment]
とりあえず起動と終了、起動中に定間隔でCPU及びメモリ使用率をログに吐き出させる形で

**Comment by domasyake** [comment]
起動時間はとりあえずログで吐き出すようにしてる

**Comment by domasyake** [comment]
52340e5f7652b0ee092ffeee10d60925866e9fc8
